accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    # 팔로우
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('profile/<username>/', views.profile, name='profile'),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
# 이미지 업로드
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_pk>/', views.detail, name='detail'),
    # 게시글 생성
    path('create/', views.create, name='create'),
    # 선택
    path('<int:post_pk>/select/<str:answer>/', views.select, name='select'),
    # 게시글 좋아요
    path('<int:post_pk>/likes/', views.likes, name="likes"),
    # 댓글 작성
    path('<int:post_pk>/comments/', views.comment_create, name='comment_create'),
    # 댓글 좋아요
    path('<int:post_pk>/comments/<int:comment_pk>/', views.comment_like, name='comment_like'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')

posts/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill

class Post(models.Model):
    title           = models.CharField(max_length=20)
    user            = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users      = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')
    select1_content = models.TextField(max_length=200)
    select1_image   = models.ImageField(blank=True, upload_to='images/')
    select2_content = models.TextField(max_length=200)
    select2_image   = models.ImageField(blank=True, upload_to='images/')
    select1_user    = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='select1_post')
    select2_user    = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='select2_post')
    created_at      = models.DateTimeField(auto_now_add=True)
    updated_at      = models.DateTimeField(auto_now=True)

    select1_image_thumbnail = ImageSpecField(source='select1_image',
                                      processors=[ResizeToFill(50, 100)],
                                      format='JPEG',
                                      options={'quality': 100})
    
    select2_image_thumbnail = ImageSpecField(source='select2_image',
                                      processors=[ResizeToFill(50, 100)],
                                      format='JPEG',
                                      options={'quality': 100})
    
class Comment(models.Model):
    user       = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_commnet')
    post       = models.ForeignKey(Post, on_delete=models.CASCADE)
    content    = models.TextField()

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import get_user_model
from django import forms

class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(
        max_length=30,
        required=True,
        label='아이디',
        widget=forms.TextInput(
            attrs={
                'class' : 'form-control',
                'placeholder' : '영문 소문자 또는 영문 대문자, 숫자 조합 6~12자리'
            }
        )
    )

    email = forms.EmailField(
        max_length=254,
        required=True,
        label='이메일',
        widget= forms.TextInput(
            attrs={
                'class' : 'form-control',
                'placeholder' : '이메일 입력'
            }
        )
    )

    first_name = forms.CharField(
        max_length=30,
        required=True, 
        label="이름",
        widget= forms.TextInput(
        attrs={
            'class' : 'form-control',
            'placeholder' : '이름 입력'
        })
    )

    last_name = forms.CharField(
        max_length=30,
        required=True, 
        label="성",
        widget= forms.TextInput(
        attrs={
            'class' : 'form-control',
            'placeholder' : '성 입력'
        })
    )

    password1 = forms.CharField(
        label="비밀번호",
        widget=forms.PasswordInput(
        attrs={
            'class' : 'form-control',
            'placeholder' : '영문, 숫자, 특수문자(~!@#$%^&*) 조합 8~15 자리'
        })
    )

    password2 = forms.CharField(
        label="비밀번호 확인",
        widget=forms.PasswordInput(
        attrs={
            'class' : 'form-control',
            'placeholder' : '비밀번호 확인'
        })
    )

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2',)

class CustomUserChangeForm(UserChangeForm):
    email = forms.EmailField(
        max_length=254, 
        required=True, 
        label="이메일",
        widget= forms.TextInput(
        attrs={
            'class' : 'form-control',
            'placeholder' : '이메일 입력'
        })
    )
        
    first_name = forms.CharField(
        max_length=30,
        required=True, 
        label="이름",
        widget= forms.TextInput(
        attrs={
            'class' : 'form-control',
            'placeholder' : '이름 입력'
        })
    )

    last_name = forms.CharField(
        max_length=30,
        required=True, 
        label="성",
        widget= forms.TextInput(
        attrs={
            'class' : 'form-control',
            'placeholder' : '성 입력'
        })
    )
    
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('email', 'first_name', 'last_name',)


class CustomUserAuthenticationForm(AuthenticationForm):
    username = forms.CharField(
        max_length=30,
        required=True,
        label="아이디",
        widget= forms.TextInput(
        attrs={
            'class' : 'form-control',
            'placeholder' : '아이디 입력'
        })
    )

    password = forms.CharField(
        label="비밀번호",
        widget=forms.PasswordInput(
        attrs={
            'class' : 'form-control',
            'placeholder' : '비밀번호 입력'
        })
    )


class CustomUserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        label="기존 비밀번호",
        widget=forms.PasswordInput(
        attrs={
            'class' : 'form-control',
            'placeholder' : '기존 비밀번호 입력'
        })
    )

    new_password1 = forms.CharField(
        label="새 비밀번호",
        widget=forms.PasswordInput(
        attrs={
            'class' : 'form-control',
            'placeholder' : '새 비밀번호 입력'
        })
    )

    new_password2 = forms.CharField(
        label="새 비밀번호 확인",
        widget=forms.PasswordInput(
        attrs={
            'class' : 'form-control',
            'placeholder' : '새 비밀번호 확인'
        })
    )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login, logout as auth_logout, update_session_auth_hash
from .forms import CustomUserChangeForm, CustomUserCreationForm, CustomUserAuthenticationForm, CustomUserPasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.http import JsonResponse

# Create your views here.
def login(request):
    if request.user.is_authenticated:
        return redirect('posts:index')
    if request.method == 'POST':
        form = CustomUserAuthenticationForm(request ,request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('posts:index')
    else:
        form = CustomUserAuthenticationForm()
    context = {
        'form':form,
    }
    return render(request,'accounts/login.html', context)

@login_required
def logout(request):
    if request.user.is_authenticated:
       auth_logout(request)
    return redirect('posts:index')

def signup(request):
    if request.user.is_authenticated:
        return redirect('posts:index')
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request,user)
            return redirect('posts:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form':form,
    }
    return render(request,'accounts/signup.html', context)

@login_required
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect('posts:index')

@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('posts:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form':form,
    }
    return render(request, 'accounts/update.html', context)

@login_required
def change_password(request):
    if request.method == 'POST':
        form = CustomUserPasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('posts:index')
    else:
        form = CustomUserPasswordChangeForm(request.user)
    context = {
        'form':form,
    }
    return render(request, 'accounts/change_password.html', context)


def profile(request, username):
    User = get_user_model()
    person = User.objects.prefetch_related('followings', 'followers', 'post_set','comment_set').get(username=username)

    comments = person.comment_set.select_related('post').all()
    
    context = {
        'person': person,
        'comments':comments,
    }
    return render(request, 'accounts/profile.html', context)


@login_required
def follow(request, user_pk):
    user = get_user_model()
    you = user.objects.get(pk=user_pk)
    me = request.user

    # 자기 자신 팔로우 x
    if you != me:
        # 이미 팔로우 중
        if me in you.followers.all():
            you.followers.remove(me)
            is_followd = False
        else:
            you.followers.add(me)
            is_followd = True
        context = {
            'is_followed'     : is_followd,
            'followings_count': you.followings.count(),
            'followers_count' : you.followers.count(),
        }
        return JsonResponse(context)
    return redirect('accounts:profile', you.username)

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/change_password.css' %}">
{% endblock style %}

{% block content %}
<div class='mt-5 mb-5 d-flex justify-content-center'>
  <form action="{% url 'accounts:change_password' %}" method="POST">
    {% csrf_token %}
    <div class="password-size">
      {{ form.as_p }}
    </div>
    <input type="submit" value="비밀번호 변경" class="btn btn-success fw-bold" style="width:100%; padding:15px;">
  </form>
</div>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
<form action="{% url 'accounts:login' %}" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="로그인" class="btn btn-success fw-bold" style="width:100%; padding:20px; font-size:22px;">
</form>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block style %}

{% endblock style %}
{% block content %}
<div class="container">
  <div class="row">
    <h1>{{ person.username }} 님의 프로필 페이지</h1>
    <!-- 팔로우 버튼 -->
    {% if request.user.is_authenticated %}
      {% if request.user != person %}
        <form id="follow-form" data-user-id="{{ person.pk }}" >
          {% csrf_token %}
          {% if request.user in person.followers.all %}
            <input type="submit" value="언팔로우" class="btn btn-primary">
          {% else %}
            <input type="submit" value="팔로우" class="btn btn-primary">
          {% endif %}
        </form>
      {% else %}
      {% endif %}
    {% else %}
			<input type="submit" value="팔로우" class="btn btn-primary disabled">
    {% endif %}
	</div>

  <!-- Button trigger modal -->
  <div class="d-flex">
		<div class="mx-2">
			<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal1">
				팔로잉 {{ person.followings.count }} 명
			</button>
		</div>
		<div class="mx-2">
			<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal2">
				팔로워 <span id="followers-count">{{ person.followers.count }}</span> 명
			</button>
		</div>
		<div class="mx-2">
			<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal3">
				맞팔 목록
			</button>
		</div>
	</div>

  <div class="row">
		<h2>{{ person.username }} 님이 좋아요한 글</h2>
		{% for post in person.like_posts.all %}
			<a href="{% url 'posts:detail' post.pk %}">
				{{ post.title }}
			</a>
		{% endfor %}
		<hr> 
	</div>
	<div class="row">
		<h2>{{ person.username }} 님이 작성한 글</h2>
		{% for post in person.post_set.all %}
			<a href="{% url 'posts:detail' post.pk %}">
				{{ post.title }}
			</a>
		{% endfor %}
		<hr> 
	</div>
	<div class="row">
		<h2>{{ person.username }} 님이 작성한 댓글</h2>
		{% for comment in  comments %}
		<p>
			<a href="{% url 'posts:detail' comment.post.pk %}">
				{{ comment.content }}
			</a>
		</p>
		{% endfor %}
		<hr>
	</div>

	<!-- Modal -->
	{# following #}
	<div class="modal fade" id="exampleModal1" tabindex="-1" aria-labelledby="exampleModalLabel1" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h1 class="modal-title fs-5" id="exampleModalLabel1">{{ person.username }} 님의 팔로잉 목록</h1>
					<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
				</div>
				<div class="modal-body">
					{% for following in person.followings.all %}
						<p><a href="{% url 'accounts:profile' following.username %}">{{ following.username }}</a></p>
					{% endfor %}
				</div>
			</div>
		</div>
	</div>
	{# follower #}
	<div class="modal fade" id="exampleModal2" tabindex="-1" aria-labelledby="exampleModalLabel2" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h1 class="modal-title fs-5" id="exampleModalLabel2">{{ person.username }} 님의 팔로워 목록</h1>
					<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
				</div>
				<div class="modal-body">
					{% for follower in person.followers.all %}
						<p><a href="{% url 'accounts:profile' follower.username %}">{{ follower.username }}</a></p>
					{% endfor %}
				</div>
			</div>
		</div>
	</div>
	{# following & follower #}
	<div class="modal fade" id="exampleModal3" tabindex="-1" aria-labelledby="exampleModalLabel3" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h1 class="modal-title fs-5" id="exampleModalLabel3">{{ person.username }} 님의 맞팔 목록</h1>
					<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
				</div>
				<div class="modal-body">
					{% for follower in person.followers.all %}
						{% if person in follower.followers.all %}
						<p>
							<a href="{% url 'accounts:profile' follower.username %}">{{ follower.username }}</a>
						</p>
						{% endif %}
					{% endfor %}
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock content %}

{% block script %}
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="{% static 'js/profile.js' %}"></script>
{% endblock script %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'accounts:signup' %}" method = "POST">
  {% csrf_token %}
  <div class="signup-size">
    {{ form.as_p }}
  </div>
  <input type="submit" value='회원 가입' class="btn btn-success fw-bold  mb-5" style="width:100%; padding:15px; font-size: 22px;"> 
  </div>
</form>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block content %}
<div class='d-flex justify-content-center'>
  <form action="{% url 'accounts:update' %}" method = "POST">
    {% csrf_token %}
    <div class="update-size mt-5 mb-5">
      <div class="mb-2">
        <label>이메일</label>
        {{ form.email }}
      </div>
      <div class="mb-2">
        <label>성</label>
        {{ form.first_name }}
      </div>
      <div class="mb-2">
        <label>이름</label>
        {{ form.last_name }}
      </div>
    </div>
    <input type="submit" value='회원정보 수정' class="btn btn-success mb-3" style="width:100%; padding:20px; font-size: 21px;"> 
    <a class="change-password btn btn-success" style="width:100%; padding:20px; font-size: 22px;" on-click='func()' href="{% url 'accounts:change_password' %}">비밀번호 변경</a>
  </form>
</div>
{% endblock content %}