accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    # 팔로우
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('profile/<username>/', views.profile, name='profile'),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
# 이미지 업로드
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_pk>/', views.detail, name='detail'),
    # 게시글 생성
    path('create/', views.create, name='create'),
    # 선택
    path('<int:post_pk>/select/<str:answer>/', views.select, name='select'),
    # 게시글 좋아요
    path('<int:post_pk>/likes/', views.likes, name="likes"),
    # 댓글 작성
    path('<int:post_pk>/comments/', views.comment_create, name='comment_create'),
    # 댓글 좋아요
    path('<int:post_pk>/comments/<int:comment_pk>/', views.comment_like, name='comment_like'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  <link rel="stylesheet" href="{% static 'css/nav.css' %}">
  <style>
  </style>
  {% block style %}
  {% endblock style %}
  <title>{% block title %}BALANCE GAME{% endblock title %}</title>
</head>
<body>
  <!-- navbar -->
  {% include 'nav.html' %}

  {% block content %}
  {% endblock content %}
  
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  {% block script %}
  {% endblock script %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
<div class="text-center">
  <h1><a href="{% url 'posts:index' %}">GO!!</a></h1>
</div>
{% endblock content %}

templates/nav.html
<nav class="sticky-top bg-white text-success-emphasis mb-4 border-bottom border-success-subtle">
  <div class="container h p-0">
    <div class="row d-flex justify-content-between p-0">
      <div class="h p-0 col-4 d-flex align-items-center justify-content-start">
        <a class="h mt-4 text-success-emphasis d-flex justify-content-start" href="{% url 'posts:index' %}" style="color:#006400;text-decoration-line:none;font-size:large;">
          BALANCE GAME
        </a>
      </div>
      <div class="h p-0 col-8 d-flex justify-content-end">
        {% if user.is_authenticated %}
          <p class="h mt-4 m-0 me-3 pe-1 hidden">
            <a class="h mt-3 link-success link-underline-light m-1 align-items-center" style="text-decoration-line:none;" href="{% url 'accounts:profile' user %}">
              {{ user }}
            </a> 님 안녕하세요!
          </p>
          <form class="text-white" action="{% url 'accounts:logout' %}" method="POST">
            {% csrf_token %}
            <a href="{% url 'accounts:update' %}"  class="btn btn-success me-1 mt-3 ">회원정보 수정</a>
            <input class="btn btn-success mt-3" type="submit" value="로그아웃">
          </form>
        {% else %}
          <div class="h p-0 col-8 d-flex align-items-center justify-content-end">
            <a href="{% url 'accounts:login' %}" class="btn btn-success ms-3 me-1 mt-3">로그인</a>
            <a href="{% url 'accounts:signup' %}" class="btn btn-success ms-1 me-1 mt-3">회원가입</a>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
</nav>