accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    # 팔로우
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('profile/<username>/', views.profile, name='profile'),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
# 이미지 업로드
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_pk>/', views.detail, name='detail'),
    # 게시글 생성
    path('create/', views.create, name='create'),
    # 선택
    path('<int:post_pk>/select/<str:answer>/', views.select, name='select'),
    # 게시글 좋아요
    path('<int:post_pk>/likes/', views.likes, name="likes"),
    # 댓글 작성
    path('<int:post_pk>/comments/', views.comment_create, name='comment_create'),
    # 댓글 좋아요
    path('<int:post_pk>/comments/<int:comment_pk>/', views.comment_like, name='comment_like'),
]

posts/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill

class Post(models.Model):
    title           = models.CharField(max_length=20)
    user            = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users      = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')
    select1_content = models.TextField(max_length=200)
    select1_image   = models.ImageField(blank=True, upload_to='images/')
    select2_content = models.TextField(max_length=200)
    select2_image   = models.ImageField(blank=True, upload_to='images/')
    select1_user    = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='select1_post')
    select2_user    = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='select2_post')
    created_at      = models.DateTimeField(auto_now_add=True)
    updated_at      = models.DateTimeField(auto_now=True)

    select1_image_thumbnail = ImageSpecField(source='select1_image',
                                      processors=[ResizeToFill(50, 100)],
                                      format='JPEG',
                                      options={'quality': 100})
    
    select2_image_thumbnail = ImageSpecField(source='select2_image',
                                      processors=[ResizeToFill(50, 100)],
                                      format='JPEG',
                                      options={'quality': 100})
    
class Comment(models.Model):
    user       = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_commnet')
    post       = models.ForeignKey(Post, on_delete=models.CASCADE)
    content    = models.TextField()

posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ('user', 'like_users', 'select1_user', 'select2_user')

    title = forms.CharField(
        label='title',
        widget=forms.TextInput(
          attrs={
            'class' : 'form-control',
            'placeholder' : '제목을 입력해주세요',
          }
        )
    )
    select1_content = forms.CharField(
        label='content',
        widget=forms.Textarea(
          attrs={
            'class' : 'form-control',
            'placeholder' : '내용을 입력해주세요'
          }
        )
    )    
    select2_content = forms.CharField(
        label='content',
        widget=forms.Textarea(
          attrs={
            'class' : 'form-control',
            'placeholder' : '내용을 입력해주세요'
          }
        )
    )
        

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
    content = forms.CharField(
        label='content', 
        widget= forms.TextInput(
        attrs={
            'class' : 'form-control',
            'style' : 'width : 500px',
            'placeholder' : '댓글을 써주세요'
        }
        )
    )

posts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.db.models import Count
from django.utils import timezone
from datetime import timedelta
from django.http import JsonResponse
# Create your views here.

def index(request):
    posts = Post.objects.order_by('-pk')

    get_date_filter = request.GET.get('date_filter','')
    posts = filter_date(posts, get_date_filter)

    get_order = request.GET.get('order','')
    posts = sort_order(posts, get_order)

    context = {
        'posts': posts,
        'get_order': get_order,
    }
    return render(request, 'posts/index.html', context)


def filter_date(queryset, date_filter):
    if date_filter:
        date_filter = int(date_filter)
        return queryset.filter(created_at__gte=timezone.now()-timedelta(days=date_filter))
    else:
        return queryset


def sort_order(queryset, order):
    if order == 'voter':
        return queryset.alias(voter=(Count('select1_user')+Count('select2_user'))).order_by('-voter')
    elif order == 'likes':
        return queryset.alias(likes=Count('like_users')).order_by('-likes')
    elif order == 'newest':
        return queryset.order_by('-pk')
    elif order == 'old':
        return queryset.order_by('pk')
    else:
        return queryset


def detail(request, post_pk):
    # 역참조 및 m:n - prefetch_related
    # 정참조 - select_related

    # 게시글
    post = Post.objects.select_related('user').prefetch_related(
                                        'comment_set', 'select1_user',
                                        'select2_user', 'like_users').get(pk=post_pk)

    select1_user_count = post.select1_user.count()
    select2_user_count = post.select2_user.count()
    
    # 댓글
    comments = post.comment_set.select_related('user').prefetch_related('like_users').all()
    get_order = request.GET.get('order','')
    comments = sort_order(comments, get_order)
    
    comment_form = CommentForm()

    context = {
        'post': post,
        'select1_user_count':select1_user_count,
        'select2_user_count':select2_user_count,
        'comments': comments,
        'comment_form': comment_form,
    }
    return render(request, 'posts/detail.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            # 저장 x, 인스턴스만 생성
            post = form.save(commit=False)
            post.user = request.user
            # 저장
            post.save()
            return redirect('posts:detail', post.pk)
    else:
        form = PostForm()
    context = {
        'form': form,
    }
    return render(request, 'posts/create.html', context)

@login_required
def select(request, post_pk, answer):
    post = Post.objects.get(pk=post_pk)
    user = request.user
    if user in post.select1_user.all() or user in post.select2_user.all():
        return redirect('posts:detail', post_pk=post_pk)

    if answer == post.select1_content:
        post.select1_user.add(user)
    elif answer == post.select2_content:
        post.select2_user.add(user)
    else:
        return redirect('posts:detail', post_pk=post_pk)

    return redirect('posts:detail', post_pk=post_pk)


@login_required
def comment_create(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.user = request.user
        comment.post = post
        comment.save()
    return redirect('posts:detail', post.pk)

#게시글 좋아요
@login_required
def likes(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    if post.like_users.filter(pk=request.user.pk).exists():
        post.like_users.remove(request.user)
        is_liked = False
    else:
        post.like_users.add(request.user)
        is_liked = True
    
    # 게시글 좋아요 수
    post_like_count = post.like_users.count()
    
    context = {
          'is_liked': is_liked,
          'post_like_count': post_like_count,
    }
    return JsonResponse(context)


# 댓글 좋아요
@login_required
def comment_like(request, post_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)

    # 이미 좋아요 한 경우
    if comment.like_users.filter(pk=request.user.pk).exists():
        comment.like_users.remove(request.user)
    else:
        comment.like_users.add(request.user)
    return redirect('posts:detail', post_pk)

posts/templates/posts/create.html
{% extends 'base.html' %}

{% block content %}
<div class="mt-5 container d-flex justify-content-center" style="width:70%">
  <form action="{% url 'posts:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="d-flex justify-content-center btn btn-success" type="submit" value="주제 작성">
  </form>
</div>
{% endblock content %}

posts/templates/posts/detail.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
{% endblock style %}

{% block content %}

<div class="container">
    <div class="row">
      <p class="mt-4" style="color:#006400; font-size:x-large">{{ post.title }}</p>
    </div>
    <div class="row">
      <p class="d-flex justify-content-end">
        <a style="color:#006400; text-decoration-line:none; font-size:large" href="{% url 'accounts:profile' post.user %}">
          {{ post.user }}</a> 님이 작성</p>
      <p id="post-like-count" class="d-flex justify-content-end">
        좋아요: {{ post.like_users.count }}
      </p>
    </div>
    <div class="row mt-5 d-flex justify-content-center">
      <div class="col-3 d-flex flex-column justify-content-center" style="align-items-stretch">
        <p class="d-flex justify-content-center" style="font-size:large">{{ post.select1_content }}</p>
          <div class="mt-3 d-flex justify-content-center">
            {% if post.select1_image %}
              <img class="mt-3 d-flex justify-content-center" src="{{ post.select1_image.url }}" alt="" width='200px' height='200px'>
            {% else %}
              <img class="mt-3 d-flex justify-content-center" src="{% static 'no-image.png' %}" alt="no-img" width="200px" height="200px">
            {% endif %}
          </div>
          <form class="mt-5 d-flex justify-content-center" action="{% url 'posts:select' post_pk=post.pk answer=post.select1_content %}">
            {% csrf_token %}
            {% if request.user in post.select1_user.all or request.user in post.select2_user.all %}
              <button class="btn btn-outline-success disabled" type="submit">선택</button>
            {% else %}
              <button class="btn btn-outline-success" type="submit">선택</button>
            {% endif %}
          </form>
          <p class="mt-3 d-flex justify-content-center">{{ select1_user_count }}</p>
        </div>
        
        {% comment %} 원형그래프 {% endcomment %}
        <div class='col-6' style="width:300px; height:300px;">
          {% if request.user in post.select1_user.all or request.user in post.select2_user.all %}
            <canvas id="myChart"></canvas>
            <script>
              var ctx = document.getElementById('myChart').getContext('2d');
              var myChart = new Chart(ctx, {
                type: 'pie',
                data: {
                  labels: ['{{ post.select1_content }}', '{{ post.select2_content }}'],
                  datasets: [{
                    label: 'Vote Results',
                    data: [{{ post.select1_user.count }}, {{ post.select2_user.count }}],
                    backgroundColor: [
                      'rgba(190,245,190,1)',
                      'rgba(160,223,225,1)',
                    ],
                    borderWidth: 1
                  }]
                },
                options: {
                  responsive: true,
                  maintainAspectRatio: false
                }
              });
            </script>
          {% else %}
          
          {% endif %}
          
        </div>

        <div class="col-3 d-flex flex-column justify-content-center" style="align-items-stretch">
          <p class="d-flex justify-content-center" style="font-size:large">{{ post.select2_content }}</p>
          <div class="mt-3 d-flex justify-content-center">
            {% if post.select2_image %}
              <img class="mt-3 d-flex justify-content-center" src="{{ post.select2_image.url }}" alt="" width='200px' height='200px'>
            {% else %}
              <img class="mt-3 d-flex justify-content-center" src="{% static 'no-image.png' %}" alt="no-img" width="200px" height="200px">
            {% endif %}
          </div>
          <form class="mt-5 d-flex justify-content-center" action="{% url 'posts:select' post_pk=post.pk answer=post.select2_content %}">
            {% csrf_token %}
            {% if request.user in post.select1_user.all or request.user in post.select2_user.all %}
              <button class="btn btn-outline-success disabled" type="submit">선택</button>
            {% else %}
              <button class="btn btn-outline-success" type="submit">선택</button>
            {% endif %}
          </form>
          <p class="mt-3 d-flex justify-content-center">{{ select2_user_count }}</p>
      </div>
    </div>


    {# 게시글 좋아요 #}
    <div class="d-flex justify-content-end">
      <form class="mt-5" id="like-forms" data-post-id="{{ post.pk }}">
        {% csrf_token %}
        {% if request.user.is_authenticated %}
          {% if request.user in post.like_users.all %}
            <input class="btn btn-outline-success" type="submit" value="좋아요 취소" id="like--{{ post.pk }}">
          {% else %}
            <input class="btn btn-outline-success" type="submit" value="좋아요 {{ post.like_users.count }}" id="like--{{ post.pk }}">
          {% endif %}
        {% else %}
          <input class="btn btn-outline-success" type="submit" value="좋아요 {{ post.like_users.count }}" disabled>
        {% endif %}
    </div>
    </form>

    {# 댓글 #}
    <form class="ms-4 d-flex justify-content-start text-center align-self-center" action="{% url 'posts:comment_create' post.pk %}" method="POST">
      {% csrf_token %}
      {{ comment_form.as_p }}
      <div class="ms-3 d-flex justify-content-center align-self-center">
        <input class="btn btn-success" type="submit" value="댓글 작성">
      </div>
    </form>
    <hr>
    <div class="mb-5">
      <div class="d-flex justify-content-between align-items-center">
        <div>
          <form action="{% url 'posts:detail' post.pk %}" method="GET">
            <button class="btn btn-success" type="submit" name="order" value="likes">좋아요순</button>
            <button class="btn btn-success" type="submit" name="order" value="newest">최신순</button>
            <button class="btn btn-success" type="submit" name="order" value="old">오랜순</button>
          </form>
        </div>
        <div class="" style="color:#198754;">
        {% comment %} <div class="me-4 mb-4 d-flex justify-content-end" style="color:#198754;"> {% endcomment %}
          댓글 수 : ({{ comments | length }})
        </div>
      </div>
      <div class="mt-3 d-flex justify-content-start">
        <ul>
          <div>
            {% for comment in comments %}
            <div class="d-flex justify-content-start">
              <li class="mb-2 d-flex justify-content-start text-center align-self-center">
                <p class="mt-3 d-flex justify-content-start text-center align-self-center">
                  <div class="ms-3 d-flex justify-content-center text-center align-self-center">
                    <a href="{% url 'accounts:profile' comment.user %}" style="color:#006400; text-decoration-line:none;">{{ comment.user }}</a>
                  </div>
                  <div class="ms-3 d-flex justify-content-center text-center align-self-center">
                    {{ comment.content }}
                  </div>
                  <div class="ms-3 d-flex justify-content-end text-center align-self-center">
                    👍 {{ comment.like_users.count }}
                  </div>
                </p>
                <div class="ms-5 d-flex justify-content-start text-center align-self-center">
                  <form action="{% url 'posts:comment_like' post_pk=post.pk comment_pk=comment.pk %}" method="POST">
                    {% csrf_token %}
                    {% if request.user in comment.like_users.all %}
                    <div class="ms-3 d-flex justify-content-center align-self-center">
                        <input class="btn btn-outline-success"type="submit" value='좋아요 취소'>
                    </div>
                    {% else %}
                    <div class="ms-3 d-flex justify-content-center align-self-center">
                        <input class="btn btn-outline-success" type="submit" value='좋아요'>
                    </div>
                    {% endif %}
                  </form>
                </div>
              </li>
            </div>
            {% endfor %}
          </div>
        </ul>
      </div>
    </div>
</div>

{% comment %} 게시글 좋아요 {% endcomment %}
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script>
    const form = document.querySelector('#like-forms')
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
    console.log('test0')
    
    form.addEventListener('submit', function (event) {
      console.log('test1')
      event.preventDefault()
      const postId = event.target.dataset.postId
      axios({
        method: "POST",
        url: `/posts/${postId}/likes/`,
        headers: {'X-CSRFToken': csrftoken},
      })
        .then((response) => {
          const isLiked = response.data.is_liked
          const likeBtn = document.querySelector(`#like--${postId}`)
          if (isLiked === true) {
            likeBtn.value = '좋아요 취소'
          } else {
            likeBtn.value = '좋아요'
          }
          // 좋아요 수 태그 
          const postLikeCountTag = document.querySelector('#post-like-count')
          // view 응답 json
          const postLikeCountData = response.data.post_like_count

          postLikeCountTag.textContent = postLikeCountData
        })
        .catch((error) => {
          console.log(error.response)
        })
    })
  </script>

{% endblock content %}

posts/templates/posts/index.html
{% extends 'base.html' %}
{% load static %}


{% block style %}
{% endblock style %}

{% block content %}
<!-- 정렬 / 필터 -->
<div class="mb-5 container">
  <div class="row d-flex justify-content-evenly">
    <div class="d-flex align-items-center justify-content-end">
      <form action="{% url 'posts:index' %}" method="GET">
        <button class="btn btn-success mt-3 pt-2" type="submit" name="order" value="voter">참여순</button>
        <button class="btn btn-success mt-3 pt-2" type="submit" name="order" value="likes">좋아요순</button>
        <button class="btn btn-success mt-3 pt-2" type="submit" name="order" value="newest">최신순</button>
      </form>
    </div>
    <div class="d-flex align-items-center justify-content-end">
      <form action="{% url 'posts:index' %}" method="GET">
        <button class="btn btn-outline-success mt-3 pt-2" type="submit" name="date_filter" value="">전체</button>
        <button class="btn btn-outline-success mt-3 pt-2" type="submit" name="date_filter" value="30">월</button>
        <button class="btn btn-outline-success mt-3 pt-2" type="submit" name="date_filter" value="7">주</button>
        <button class="btn btn-outline-success mt-3 pt-2" type="submit" name="date_filter" value="1">일</button>
      </form>
    </div>   
  </div>
  <button class="mt-3 btn btn-success me-1 pt-2 d-flex justify-content-start">
    <a href="{% url 'posts:create' %}" style="color:white; text-decoration-line:none;">주제 작성</a>
  </button>
</div>

<!-- 카드 -->
<div class="mb-5 container">
  <div class="row g-4">
    {% for post in posts %}
      <div class="col-12 col-md-6 col-lg-4 col-xl-3">
          <div class="card">
            {% if post.select1_image %}
              <img src="{{ post.select1_image.url }}" class="card-img-top" width="200px" height="200px">
            {% else %}
              <img src="{% static 'no-image.png' %}" alt="no-img" width="200px" height="200px">
            {% endif %}
          <div class="card-body">
            <h5 class="card-title"><a href="{% url 'posts:detail' post.pk %}" style="color:#006400; text-decoration-line:none;">{{ post.title }}</a></h5>
            <p class="card-text">
              <div class="d-flex justify-content-center">
                {{ post.select1_content }}
              </div>
              <div class="d-flex justify-content-center">
                VS
              </div>
              <div class="d-flex justify-content-center">
                {{ post.select2_content }}
              </div>
            </p>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock content %}